/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.rulemgmt.action;

/**
 *
 * @author elmonazareno
 */
public class ActionHandlerTemplate extends javax.swing.JPanel {

    /**
     * Creates new form ActionHandlerTemplate
     */
    public ActionHandlerTemplate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xButton1 = new com.rameses.rcp.control.XButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 5, 2, 5));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        xButton1.setName("removeAction"); // NOI18N
        xButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 2, 5, 2));
        xButton1.setContentAreaFilled(false);
        xButton1.setIconResource("images/toolbars/trash.png");
        xButton1.setImmediate(true);
        xButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        xButton1.setPreferredSize(new java.awt.Dimension(25, 17));
        xButton1.setShowCaption(false);
        xButton1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(xButton1);

        add(jPanel1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XButton xButton1;
    // End of variables declaration//GEN-END:variables
}
