/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.rulemgmt.action;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(value=ActionHandlerTemplate.class)
@StyleSheet
public class FieldListHandler extends javax.swing.JPanel {

    /**
     * Creates new form FieldListHandler
     */
    public FieldListHandler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xComboBox2 = new com.rameses.rcp.control.XComboBox();

        setLayout(new java.awt.BorderLayout());

        xComboBox2.setExpression("#{item.name}");
        xComboBox2.setItems("varList");
        xComboBox2.setName("actionParam.stringvalue"); // NOI18N
        xComboBox2.setDynamic(true);
        xComboBox2.setPreferredSize(new java.awt.Dimension(214, 20));
        xComboBox2.setShowCaption(false);
        add(xComboBox2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox2;
    // End of variables declaration//GEN-END:variables
}
