/*
 * AddCondition.java
 *
 * Created on August 31, 2013, 9:17 AM
 */

package com.rameses.rulemgmt;

import com.rameses.osiris2.themes.CloseOnlyPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  Elmo
 */
@Template(CloseOnlyPage.class)
@StyleSheet
public class SelectActionPage extends javax.swing.JPanel {
    
    /** Creates new form AddCondition */
    public SelectActionPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xList1 = new com.rameses.rcp.control.XList();
        jPanel1 = new javax.swing.JPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        xButton2 = new com.rameses.rcp.control.XButton();
        xButton3 = new com.rameses.rcp.control.XButton();
        xButton4 = new com.rameses.rcp.control.XButton();
        xButton5 = new com.rameses.rcp.control.XButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(654, 400));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("<html><b>Select Action</b></html>");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        add(jLabel1, java.awt.BorderLayout.NORTH);

        xList1.setExpression("#{item.title}");
        xList1.setItems("actionDefList");
        xList1.setName("selectedActionDef"); // NOI18N
        xList1.setDynamic(true);
        xList1.setFixedCellHeight(18);
        jScrollPane1.setViewportView(xList1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 0, 0));
        com.rameses.rcp.control.layout.XLayout xLayout1 = new com.rameses.rcp.control.layout.XLayout();
        xLayout1.setSpacing(3);
        jPanel1.setLayout(xLayout1);

        xButton1.setCaption("Next");
        xButton1.setMnemonic('N');
        xButton1.setName("doNext"); // NOI18N
        xButton1.setText("Next");
        jPanel1.add(xButton1);
        jPanel1.add(filler2);

        xButton2.setCaption("New");
        xButton2.setMnemonic('w');
        xButton2.setName("addActionDef"); // NOI18N
        xButton2.setText("New");
        jPanel1.add(xButton2);

        xButton3.setCaption("New");
        xButton3.setMnemonic('E');
        xButton3.setName("editActionDef"); // NOI18N
        xButton3.setText("Edit");
        jPanel1.add(xButton3);

        xButton4.setCaption("Refresh");
        xButton4.setMnemonic('R');
        xButton4.setName("reloadList"); // NOI18N
        xButton4.setText("Refresh");
        jPanel1.add(xButton4);

        xButton5.setCaption("New");
        xButton5.setMnemonic('m');
        xButton5.setName("removeActionDef"); // NOI18N
        xButton5.setText("Remove");
        jPanel1.add(xButton5);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XButton xButton3;
    private com.rameses.rcp.control.XButton xButton4;
    private com.rameses.rcp.control.XButton xButton5;
    private com.rameses.rcp.control.XList xList1;
    // End of variables declaration//GEN-END:variables
    
}
