/*
 * RuleConstraintTemplate.java
 *
 * Created on September 30, 2013, 9:05 AM
 */

package com.rameses.rulemgmt.constraint;

/**
 *
 * @author  Elmo
 */
public class HandlerTemplate extends javax.swing.JPanel {
    
    /** Creates new form RuleConstraintTemplate */
    public HandlerTemplate() {
        initComponents();
        xButton1.setContentAreaFilled(false);
        xButton1.setBorder(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xButton1 = new com.rameses.rcp.control.XButton();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(0, 23));
        xButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        xButton1.setIconResource("images/toolbars/trash.png");
        xButton1.setImmediate(true);
        xButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        xButton1.setName("removeConstraint");
        xButton1.setPreferredSize(new java.awt.Dimension(25, 17));
        xButton1.setShowCaption(false);
        add(xButton1, java.awt.BorderLayout.EAST);

        xFormPanel1.setPadding(new java.awt.Insets(0, 0, 0, 5));
        xFormPanel1.setPreferredSize(new java.awt.Dimension(80, 50));
        xTextField1.setName("constraint.varname");
        xTextField1.setPreferredSize(new java.awt.Dimension(60, 20));
        xTextField1.setShowCaption(false);
        xTextField1.setSpaceChar('_');
        xFormPanel1.add(xTextField1);

        add(xFormPanel1, java.awt.BorderLayout.WEST);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
    
}
